@startuml Sports Bracket

skinparam classAttributeIconSize 0
skinparam classFontSize 13
skinparam shadowing false

skinparam class {
    BackgroundColor<<Aggregate Root>> #E3F2FD
    BorderColor<<Aggregate Root>> #1565C0
    FontColor<<Aggregate Root>> #1565C0
    HeaderBackgroundColor<<Aggregate Root>> #BBDEFB

    BackgroundColor<<Entity>> #FFF8E1
    BorderColor<<Entity>> #F57F17
    FontColor<<Entity>> #F57F17
    HeaderBackgroundColor<<Entity>> #FFE082

    BackgroundColor<<Value Object>> #F1F8E9
    BorderColor<<Value Object>> #558B2F
    FontColor<<Value Object>> #558B2F
    HeaderBackgroundColor<<Value Object>> #DCEDC8
}

skinparam package {
    BackgroundColor #FAFAFA
    BorderColor #BDBDBD
    BorderStyle dashed
    FontSize 14
}


skinparam ArrowColor #444441

package "Tournament" <<Frame>> {

    class TournamentSession <<Aggregate Root>>{

                - tournament : Tournament
                - tournamentState : TournamentSessionState
                - startDate : LocalDate
                - endDate : LocalDate
                - teams : List<Team>
    }

    /'
      Pensando de uma maneira racional, os tournaments não poderão ser considerados como value objetcs uma vez que possuem ID's.

      Podemos utilizar um mesmo torneio, desde que possamos alterar o startDate e o endDate.

      Tendo isto em conta, o startDate e endDate deixa de fazer sentido dentro do tournament e terão que ser movidos para dentro do TournamentSession
    '/

    /'
        Quando é que uma equipa pode ser considerada como vencedora?

    '/

    class Tournament <<Entity>>{

                - code : String
                - maxTeams : int
    }

    enum TournamentSessionState <<Value Object>>{

                 CONCLUDED,
                 DRAFTED,
                 PAUSED,
                 IN_PROGRESS

    }

}

package "Team" <<Frame>>{

    class Team <<Aggregate Root>>{

            - name : String
            - numberLosses : int
            - numberWins : int

    }

}

package "Match" <<Frame>>{

    class Match <<Aggregate Root>>{

        - teamOne : Team
        - teamSecond : Team
        - winningTeam : Team
        - leftRound : Match
        - rightRound : Match
    }

}




@enduml